config/routes.rb
Rails.application.routes.draw do
  root 'servers#index'
  resources :servers

end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :ip_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<%= image_tag "RubyTreeLogo.jpg" %>

<p id="notice"><%= notice %></p>

<h1>Listing Servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.ip_address %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @server.ip_address %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>